MySite/urls.py
from django.contrib import admin
from django.urls import include, path

from MySite import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin1'),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import include, path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('api/create-toilet/', views.toilet_api),

    path('api/getcomments_api/', views.getComments_api),
    path('api/addComment_api/', views.addComment_api),

    path('api/addReview_api/', views.addReviews_api),    
    path('api/getReview_api/', views.getReview_api),
]

users/urls.py
from django.urls import include, path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]
 

main/models.py
from django.db import models

# Create your models here.

class Toilets(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True,null=True,verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True,null=True, verbose_name='Изображение')
    coords1 = models.FloatField(verbose_name='Координата 1')
    coords2 = models.FloatField(verbose_name='Координата 2')

    
    class Meta:
        db_table = 'toilet'
        verbose_name = 'Туалет'
        verbose_name_plural= 'Туалеты'


    def __str__(self):
        return self.name
    

class Comments(models.Model):
    
    text = models.TextField(blank=True,null=True,verbose_name='текст')
    toilet = models.ForeignKey(to=Toilets, on_delete=models.CASCADE, verbose_name='Туалет')

    class Meta:
        db_table = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural= 'Комментарии'


    def __str__(self):
        return f'{self.toilet} comment {self.id}'
    

class Reviews(models.Model):
    
    estimation = models.IntegerField(verbose_name='оценка')
    toilet = models.ForeignKey(to=Toilets, on_delete=models.CASCADE, verbose_name='Туалет')

    class Meta:
        db_table = 'reviews'
        verbose_name = 'Отзыв'
        verbose_name_plural= 'Отзывы'


    def __str__(self):
        return f'{self.toilet} review {self.estimation}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')


    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural= 'Пользователи'


    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    
    username = forms.CharField()
    password = forms.CharField()
    class Meta:
        model = User
        fields = ['username', 'password']



class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()



class ProfileForm(UserChangeForm):
    
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        )
    
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt

from main.models import Toilets, Comments, Reviews

def index(request):

    toilets = Toilets.objects.all()


    context = {
        'toilets': toilets
    }

    return render(request, 'main/index.html', context)


@csrf_exempt
def toilet_api(request):
    
    if request.method == 'POST':
        data = json.loads(request.body)
        toilet = Toilets.objects.create(
            name=data['name'],
            coords1=data['coords1'],
            coords2=data['coords2']
        )
        return JsonResponse({'id': toilet.id, 'success': True})




def getComments_api(request):
    x = request.GET.get('currentToilet')
    currentToilet = Toilets.objects.filter(name=x)[0]
    comments = Comments.objects.filter(toilet=currentToilet)
    commentsList = []
    for comment in comments:
        oneComm = {
            'text': comment.text,
        }
        commentsList.append(oneComm)

    return JsonResponse(commentsList, safe=False)

@csrf_exempt
def addComment_api(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        currentToilet= Toilets.objects.filter(name=data['toiletName'])[0]
        Comment = Comments.objects.create(
            text=data['text'],
            toilet=currentToilet
        )
        return JsonResponse({'id': Comment.id, 'success': True})




def getReview_api(request):
    x = request.GET.get('currentToilet')
    currentToilet = Toilets.objects.filter(name=x)[0]
    reviews = Reviews.objects.filter(toilet=currentToilet)
    generalReview = 0
    size = 0
    for review in reviews:
        generalReview += review.estimation
        size += 1
    if (size != 0):
        generalReview /= size
        generalReview = float("{0:.1f}".format(generalReview))
    
    return JsonResponse(generalReview, safe=False)

@csrf_exempt
def addReviews_api(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        currentToilet= Toilets.objects.filter(name=data['toiletName'])[0]
        review = Reviews.objects.create(
            estimation=data['myReview'],
            toilet=currentToilet
        )
        return JsonResponse({'id': review.id, 'success': True})

users/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib import auth
from django.urls import reverse
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm

def login(request):

    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
            
    else:
        form = UserLoginForm()

    context = {
        'title': 'Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)



def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main:index'))
            
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Регистрация',
        'form': form,
    }
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('user:profile'))
            
    else:
        form = ProfileForm(instance=request.user)

    context = {
        'title': 'Кабинет',
        'form': form
    }
    return render(request, 'users/profile.html', context)

@login_required
def logout(request):
    auth.logout(request)

    return redirect(reverse("main:index"))

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

users/templates/users/login.html
{% extends "main/base.html" %} {% load static %} 

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 glass-dark text-white p-4 mb-4 mx-3 rounded-4">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form action="{% url "user:login" %}" method="post">
                    {% csrf_token %}
                    
                    
                    {% if form.non_field_errors %}
                    <div class="container mt-4">
                        <div class="row justify-content-center">
                            
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    {{form.non_field_errors}}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            
                        </div>
                    </div>
                        
                    {% endif %}
                    
                    <div class="mb-3">
                        <label for="id_username" class="form-label">Имя пользователя</label>
                        <input
                            type="text"
                            class="form-control glass-input"
                            id="id_username"
                            placeholder="Введите ваше имя пользователя"
                            name="username"
                            
                            required
                            
                        />
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Пароль</label>
                        <input
                            type="password"
                            class="form-control glass-input"
                            id="id_password"
                            placeholder="Введите ваш пароль"
                            name="password"
                            required
                        />
                    </div> 

                    <button type="submit" class="mx-2 btn btn-dark btn-block ">Войти</button> 
                </form>
                <div class="mt-3"><a class="glass-a" href="#">Забыли пароль?</a> | <a class="glass-a" href="{% url "users:registration" %}">Создать аккаунт</a></div>
                <hr />
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16" />
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16" />
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16" />
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "main/base.html" %} {% load static %} {% block content %}

<style>
.hover-zoom {
    transition: transform 0.3s ease;
}

.hover-zoom:hover {
    filter: brightness(0.9);
    transform: scale(1.05);
}


</style>

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div class="glass-dark text-white p-4 rounded-4">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                
                                
                                <input type="file" class="d-none" id="id_image" accept="image/*" name="image" />
    
                                <!-- Делаем изображение кликабельным через label -->
                                <label for="id_image" >
                                    {% if user.image %}
                                        <img src="{{ user.image.url }}" 
                                            alt="Аватар пользователя" 
                                            class="img-fluid rounded-circle hover-zoom"
                                            style="max-width: 150px; cursor: pointer; display: inline-block;">
                                    {% else %}
                                        <img src="{% static 'deps/images/baseavatar.jpg' %}" 
                                            alt="Аватар пользователя" 
                                            class="img-fluid rounded-circle hover-zoom"
                                            style="max-width: 150px; cursor: pointer; display: inline-block;">
                                    {% endif %}
                                </label>
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_firstName" class="form-label">Имя*</label>
                                <input
                                    type="text"
                                    class="form-control glass-input"
                                    id="id_firstName"
                                    placeholder="Введите ваше имя"
                                    name="first_name"
                                    value="{{form.first_name.value}}"
                                    required
                                />
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger alret-dismissible fade show"> {{form.first_name.errors}} </div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_lastName" class="form-label">Фамилия*</label>
                                <input
                                    type="text"
                                    class="form-control glass-input"
                                    id="id_lastName"
                                    placeholder="Введите вашу фамилию"
                                    name="last_name"
                                    value="{{form.last_name.value}}"
                                    required
                                />
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger alret-dismissible fade show"> {{form.last_name.errors}} </div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input
                                    type="text"
                                    class="form-control glass-input"
                                    id="id_username"
                                    placeholder="Введите ваше имя пользователя"
                                    name="username"
                                    value="{{form.username.value}}"
                                    required
                                />
                                {% if form.username.errors %}
                                    <div class="alert alert-danger alret-dismissible fade show"> {{form.username.errors}} </div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input
                                    type="email"
                                    class="form-control glass-input"
                                    id="id_email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    name="email"
                                    value="{{form.email.value}}"
                                    required
                                />
                            </div>
                            {% if form.email.errors %}
                                    <div class="alert alert-danger alret-dismissible fade show"> {{form.email.errors}} </div>
                                {% endif %}
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/registration.html
{% extends "main/base.html" %} {% load static %} {% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="text-white col-md-9 glass-dark p-4 mb-5 mx-2 rounded-4">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action="{% url "user:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_firstName" class="form-label">Имя*</label>
                            <input
                                type="text"
                                class="form-control glass-input"
                                id="id_firstName"
                                placeholder="Введите ваше имя"
                                value = "{% if form.first_name.value %}
                                    {{form.first_name.value}}
                                {% endif %}" 
                                name="first_name"
                                required
                            />
                            {% if form.first_name.errors %}
                                <div class="alert alert-danger alret-dismissible fade show"> {{form.first_name.errors}} </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_lastName" class="form-label">Фамилия*</label>
                            <input
                                type="text"
                                class="form-control glass-input"
                                id="id_lastName"
                                placeholder="Введите вашу фамилию"
                                value = "{% if form.last_name.value %}
                                    {{form.last_name.value}}
                                {% endif %}"
                                name="last_name"
                                required
                            />
                            {% if form.last_name.errors %}
                                <div class="alert alert-danger alret-dismissible fade show"> {{form.last_name.errors}} </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input
                                type="text"
                                class="form-control glass-input"
                                id="id_username"
                                placeholder="Введите ваше имя пользователя"
                                value = "{% if form.username.value %}
                                    {{form.username.value}}
                                {% endif %}"
                                name="username"
                                required
                            />
                            {% if form.username.errors %}
                                <div class="alert alert-danger alret-dismissible fade show"> {{form.username.errors}} </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input
                                type="email"
                                class="form-control glass-input"
                                id="id_email"
                                placeholder="Введите ваш email"
                                value = "{% if form.email.value %}
                                    {{form.email.value}}
                                {% endif %}"
                                name="email"
                                required
                            />
                            {% if form.email.errors %}
                                <div class="alert alert-danger alret-dismissible fade show"> {{form.email.errors}} </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="password1" class="form-label">Пароль*</label>
                            <input
                                type="password"
                                class="form-control glass-input"
                                id="password1"
                                placeholder="Введите пароль"
                                name="password1"
                                required
                            />
                            {% if form.password1.errors %}
                                <div class="alert alert-danger alret-dismissible fade show"> {{form.password1.errors}} </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="password2" class="form-label">Подтверждение пароля*</label>
                            <input
                                type="password"
                                class="form-control glass-input"
                                id="password2"
                                placeholder="Подтвердите пароль"
                                name="password2"
                                required
                            />
                            {% if form.password2.errors %}
                                <div class="alert alert-danger alret-dismissible fade show"> {{form.password2.errors}} </div>
                            {% endif %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}